### ISSUE TITLE
Enhancement: The feature renaming dependency is incomplete 

### ISSUE THREAD

**Issue by zong-zhe** [kcl-lang/kpm#397]
## Problem
The current kpm renaming dependency is incomplete, the current state of this function is only to replace the dependent name in `kcl.mod`.

This will result in the following situation:

```shell
kcl mod add helloworld:0.1.0 --rename new_helloworld
```

The command above will add dependency into kcl.mod as below

```
[dependencies]
new_helloworld = 0.1.0
```

And the kcl.mod.lock
```
[dependencies]
  [dependencies.new_helloworld]
    name = "new_helloworld"
    full_name = "new_helloworld_0.1.0"
    version = "0.1.0"
```

And these incomplete information does not support updating the dependency for `helloworld` when `kcl mod update` or `kcl run`. The link between `helloworld` and `new_helloworld` is missing.

## Solution

Referring to cargo, add a `package` field to declare the association between new name and old name in `kcl.mod`.

Here is a example:
```toml
[dependencies]
new-flask-demo-kcl-manifests = { git = "https://github.com/kcl-lang/flask-demo-kcl-manifests", version = "v0.1.0", package = "flask-demo-kcl-manifests" }
flask-demo-kcl-manifests = { git = "https://github.com/kcl-lang/flask-demo-kcl-manifests", version = "v0.1.0" }

new_helloworld = { version = "1.0.0", package = "helloworld" }
helloworld = "1.0.0"
```
