### ISSUE TITLE
bug; `kcl.yaml` is has no effect 

### ISSUE THREAD

**Issue by zong-zhe** [kcl-lang/kpm#444]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Use the `kcl version 0.9.7` to compile the test case in https://github.com/kcl-lang/krm-kcl/tree/main/tests/mutation/set-annotations

1. kcl run /krm-kcl/tests/mutation/set-annotations # Use absolute path 

2. kcl run ./tests/mutation/set-annotations # Use relative paths

### 2. What did you expect to see? (Required)

The output of both commands is the same

```yaml
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: nginx
    name: nginx-deployment
    annotations: {}
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: nginx
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        - image: nginx:1.14.2
          name: nginx
          ports:
          - containerPort: 80
```

### 3. What did you see instead (Required)

`kcl run ./tests/mutation/set-annotations` outputs a normal result, but `kcl run /krm-kcl/tests/mutation/set-annotations` outputs

```
items: []
``` 

### 4. What is your KCL components version? (Required)

kcl v0.9.7
